name: Build IP lists

permissions:
    contents: read

on:
    repository_dispatch:
        types: run-build-lists
    workflow_dispatch:
    #schedule:
    #    - cron: "00 12 * * *"

jobs:
    build-stretchoid:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build the stretchoid list
              run: ./make-stretchoid.sh
            - name: Post the summary
              run: |
                git add -A
                echo '### Diff' >> $GITHUB_STEP_SUMMARY
                echo -e "\`\`\`diff\n$(git diff --staged)\n\`\`\`" >> $GITHUB_STEP_SUMMARY
